import "server-only";
import { scrypt, randomBytes, timingSafeEqual, type ScryptOptions } from "node:crypto";

/**
 * Admin password verification.
 *
 * ── Why scrypt and not Argon2id ──────────────────────────────────────────
 * Argon2id is the better algorithm on paper. In practice it means a native
 * module (`argon2` compiles at install; `@node-rs/argon2` ships prebuilt
 * binaries), and native modules on serverless are a recurring source of
 * "works locally, fails on deploy". scrypt is memory-hard, is in the RFC 7914
 * standard, ships in Node's own crypto module, adds zero dependencies and zero
 * supply-chain surface, and at these parameters is entirely adequate for a
 * single high-entropy admin password that is also rate-limited and locked out
 * server-side.
 *
 * If you later move to per-user accounts and want Argon2id, this file is the
 * only thing that changes.
 * ─────────────────────────────────────────────────────────────────────────
 *
 * ⚠ This file never receives a plaintext password from anywhere but the login
 * form, and never stores one. The hash is generated by the operator running
 * `npm run admin:hash` on their own machine.
 */

/**
 * Hand-written wrapper rather than `promisify(scrypt)`: promisify's types only
 * resolve the three-argument overload, and we need the fourth (options) to set
 * N and maxmem.
 */
function scryptAsync(
  password: string,
  salt: Buffer,
  keyLength: number,
  options: ScryptOptions,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    scrypt(password, salt, keyLength, options, (error, derivedKey) => {
      if (error) reject(error);
      else resolve(derivedKey);
    });
  });
}

/**
 * OWASP's current scrypt guidance: N ≥ 2^17, r = 8, p = 1.
 * 2^17 costs roughly 130 MB and ~150 ms — slow enough to make offline cracking
 * expensive, fast enough that a legitimate login is imperceptible.
 */
export const SCRYPT_PARAMS = {
  N: 1 << 17,
  r: 8,
  p: 1,
  keyLength: 64,
  saltLength: 32,
} as const;

/**
 * `scrypt.N.r.p.<salt-base64>.<hash-base64>`
 *
 * ── Why a dot and not the conventional `$` ────────────────────────────────
 * Because a `$` cannot survive a `.env` file. Next.js runs every value it
 * loads through dotenv-expand, which treats `$131072` as a variable reference
 * and substitutes it with nothing — turning `scrypt$131072$8$1$…` into
 * `scrypt31072…`. Single quotes do not help. Neither do double quotes, nor
 * backslash escapes; this was measured against the loader, not assumed.
 *
 * The result was a hash that failed to parse, from a value the operator had
 * copied correctly, following instructions that told them to use single quotes
 * precisely because of the `$` signs. It worked on Vercel — where variables
 * come from the platform rather than a file — and failed on every developer's
 * machine, which is close to the worst place for a bug in an auth path to hide.
 *
 * A dot is not in the base64 alphabet, so it separates the fields just as
 * unambiguously and passes through untouched. Hashes in the old format are
 * still accepted; see `verifyPassword`.
 * ─────────────────────────────────────────────────────────────────────────
 */
const FORMAT_PREFIX = "scrypt";
const SEPARATOR = ".";
/** Hashes minted before the separator changed. Still verified, never minted. */
const LEGACY_SEPARATOR = "$";

export async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(SCRYPT_PARAMS.saltLength);
  const derived = await scryptAsync(password, salt, SCRYPT_PARAMS.keyLength, {
    N: SCRYPT_PARAMS.N,
    r: SCRYPT_PARAMS.r,
    p: SCRYPT_PARAMS.p,
    // Node's default maxmem (32 MB) is too small for N = 2^17.
    maxmem: 256 * 1024 * 1024,
  });

  return [
    FORMAT_PREFIX,
    SCRYPT_PARAMS.N,
    SCRYPT_PARAMS.r,
    SCRYPT_PARAMS.p,
    salt.toString("base64"),
    derived.toString("base64"),
  ].join(SEPARATOR);
}

/**
 * Verify a candidate password against a stored hash.
 *
 * Parameters are read back out of the stored string rather than assumed, so an
 * existing hash keeps working if SCRYPT_PARAMS is raised later — and both
 * separators are accepted, so a hash minted before the format changed does not
 * lock its owner out.
 */
export async function verifyPassword(
  password: string,
  storedHash: string,
): Promise<boolean> {
  const separator = storedHash.startsWith(FORMAT_PREFIX + LEGACY_SEPARATOR)
    ? LEGACY_SEPARATOR
    : SEPARATOR;

  const parts = storedHash.split(separator);
  if (parts.length !== 6 || parts[0] !== FORMAT_PREFIX) return false;

  const N = Number(parts[1]);
  const r = Number(parts[2]);
  const p = Number(parts[3]);

  if (!Number.isInteger(N) || !Number.isInteger(r) || !Number.isInteger(p)) return false;
  // Refuse absurd parameters from a tampered env var — an attacker who could
  // set N to 2^30 would turn every login into a denial of service.
  if (N < 1 << 12 || N > 1 << 20 || r < 1 || r > 32 || p < 1 || p > 16) return false;

  let salt: Buffer;
  let expected: Buffer;
  try {
    salt = Buffer.from(parts[4], "base64");
    expected = Buffer.from(parts[5], "base64");
  } catch {
    return false;
  }

  if (salt.length === 0 || expected.length === 0) return false;

  let derived: Buffer;
  try {
    derived = await scryptAsync(password, salt, expected.length, {
      N,
      r,
      p,
      maxmem: 512 * 1024 * 1024,
    });
  } catch {
    return false;
  }

  // Constant time: `===` would leak how much of the hash matched.
  if (derived.length !== expected.length) return false;
  return timingSafeEqual(derived, expected);
}
